name: Pull Request Merged Notifier

on:
  pull_request:
    types:
      - closed

jobs:
  pull_req:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Extract PR Title, URL, and Check if Merged
      - name: Get PR Info
        run: |
          sudo apt-get install jq -y &> /dev/null
          PR_TITLE=$(jq --raw-output .pull_request.title ${GITHUB_EVENT_PATH})
          PR_URL=$(jq --raw-output .pull_request.html_url ${GITHUB_EVENT_PATH})
          PR_MERGED=$(jq --raw-output .pull_request.merged ${GITHUB_EVENT_PATH})

          echo "PR_TITLE=$PR_TITLE" >> ${GITHUB_ENV}
          echo "PR_URL=$PR_URL" >> ${GITHUB_ENV}
          echo "PR_MERGED=$PR_MERGED" >> ${GITHUB_ENV}

      # Send a notification to Telegram if PR is merged
      - name: Notify in Telegram if Merged
        run: |
          if [ "${PR_MERGED}" == "true" ]; then
            TgNotify() {
              # Send a message to Telegram
              curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" -d chat_id="${{ secrets.PRIV_CHAT_ID }}" \
              -d parse_mode=Markdown \
              -d text="${1}" \
              -d disable_web_page_preview=true || echo "Error sending message"
            }

            # Escape special characters in the PR title
            ESCAPED_TITLE=$(echo "${PR_TITLE}" | sed 's/[_*]/\\&/g')

            # Send the notification
            TgNotify "
            #PULL\_REQ\_MERGED
            *Pull Request Merged at* [${{ github.repository }}](https://github.com/${{ github.repository }})
            *Title:* \`${ESCAPED_TITLE}\`
            *User:* [${{ github.actor }}](https://github.com/${{ github.actor }})
            *Pull Req URL:* [Here](${PR_URL})"
          else
            echo "PR not merged, no notification sent."
          fi
